### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by tpoisot** [BIO6032/2022-SEIR-reproduction#1]
# Roadmap

- [x] discussion: conventions de noms de fichiers #2 
- [ ] discussion: formats des fichiers #3 
- [ ] remplir `metadata.yaml`

### Rédaction du README

- [ ] README.md ¶1: objectifs de l'article
- [ ] README.md ¶2: description du modèle
- [ ] README.md ¶3: définitions et jargon

### Vérifier diagramme (fig. 1) 

- [ ] mettre les taux et les flêches dans le bon sens #4 
- [ ] reproduire le diagramme causal avec les différents compartiments
- [ ] produire une image avec le diagramme
- [ ] ajouter la figure au dépôt git

## Programmation

- [ ] discussion: notebook ou scripts ou script + Literate.jl #5 
- [ ] discussion: packages nécessaires #6 

### Collecter les données utilisées

- [ ] identifier les valeurs des paramètres
- [ ] collecte des données utilisées - option 1: disponibles
- [ ] collecte des données utilisées - option 2: email auteur
- [ ] collecte des données utilisées - option 3: extraction manuelle
- [ ] ajouter les données dans un fichier csv, etc

### Implémentation du modèle

- [ ] définition du problème
- [ ] définir les variables
- [ ] définir les paramètres
- [ ] écrire les sytèmes d'équations
- [ ] discussion: modèle pour fig 2/3 - le même? #7 

### Effectuer les simulations

- [ ] discussion: choix des fichiers de sortie
- [ ] écrire le code pour effectuer les simulations

## Réplication

- [ ] discussion: conventions visuelles #8 
- [ ] discussion: si les figures ne correspondent pas?

### Figure - (fig. 2a)

- [ ] produire la figure brute

### Figure - (fig. 2b)

- [ ] produire la figure brute

### Figure - (fig. 3a)

- [ ] produire la figure brute

### Figure - (fig. 3b)

- [ ] produire la figure brute

## Rédaction

- [ ] lire les guidelines du journal

### Rédaction - introduction

- [ ] résumer l'objectif de l'article
- [ ] définir le contexte général
- [ ] définir les hypothèses et prémisses

### Rédaction - résultats

- [ ] information technique sur le code (license, langage, dépendances, versions)
- [ ] faire des liens entre les figures et les données
- [ ] courte description du contenu des figures
- [ ] courte interprétation des figures

### Rédaction - conclusion

- [ ] réponse: reproduction réussie ou pas?
- [ ] définir clairement comment on est parvenu aux objectifs
- [ ] discussion: disponibilité des données (si besoin)
- [ ] limitations/ alternatives ?

# Après le projet

- [ ] compiler le document @tpoisot 
- [ ] mettre à jour `metadata.yaml`
